lang: en
title: Matt's Homelab
theme: jekyll-theme-minimal
author: Matt Faulkner
#baseurl: "https://goobyfrs.github.io"
url: "https://www.goobyfrs.net"
permalink: pretty


plugins:
  - jekyll-sitemap 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme